use iced::Color;

#[derive(Debug, Clone)]
pub struct VizConfig {
    pub gradient_colors: Vec<Color>,
    pub peak_gradient_colors: Vec<Color>,
    pub border_color: Color,
    pub peak_color: Color,
    pub border_width: f32,
    pub peak_enabled: bool,
    pub peak_thickness: f32,
    pub peak_alpha: f32,
    pub line_thickness: f32,
    pub bar_width: f32,
    pub bar_spacing: f32,
    pub edge_spacing: f32,
    pub led_bars: bool,
    pub led_segment_height: f32,
    pub led_border_opacity: f32,
    pub border_opacity: f32,
    pub gradient_mode: u32,
    pub peak_gradient_mode: u32,
    pub peak_mode: u32,
    pub peak_hold_time: f32,
    pub peak_fade_time: f32,
    pub bar_depth_3d: f32,
    pub gradient_orientation: u32,
    pub global_opacity: f32,
    pub lines_outline_thickness: f32,
    pub lines_outline_opacity: f32,
    pub lines_animation_speed: f32,
    pub lines_gradient_mode: u32,
    pub lines_fill_opacity: f32,
    pub lines_mirror: bool,
    pub lines_glow_intensity: f32,
    pub lines_style: u32,
    pub scope_radius: f32,
    pub scope_sensitivity: f32,
    pub scope_particles: bool,
    pub scope_beam: bool,
    pub bars_flash_intensity: f32,
    pub bloom_enabled: bool,
    pub bloom_intensity: f32,
    pub beat_reactivity: f32,
    pub trails: f32,
    pub echo: f32,
    pub crt: f32,
}

impl Default for VizConfig {
    fn default() -> Self {
        Self {
            gradient_colors: vec![
                Color::from_rgb(0.1, 0.4, 0.9),
                Color::from_rgb(0.1, 0.6, 1.0),
                Color::from_rgb(0.0, 0.8, 1.0),
                Color::from_rgb(0.0, 1.0, 0.9),
                Color::from_rgb(0.0, 0.9, 0.7),
                Color::from_rgb(0.1, 0.7, 0.8),
                Color::from_rgb(0.2, 0.5, 0.9),
                Color::from_rgb(0.3, 0.4, 1.0),
            ],
            peak_gradient_colors: vec![
                Color::from_rgb(1.0, 0.6, 0.0),
                Color::from_rgb(1.0, 0.4, 0.0),
                Color::from_rgb(1.0, 0.2, 0.1),
                Color::from_rgb(1.0, 0.8, 0.0),
                Color::from_rgb(1.0, 0.5, 0.1),
                Color::from_rgb(0.9, 0.3, 0.0),
                Color::from_rgb(1.0, 0.7, 0.1),
                Color::from_rgb(1.0, 0.3, 0.2),
            ],
            border_color: Color::from_rgba(1.0, 1.0, 1.0, 0.15),
            peak_color: Color::WHITE,
            border_width: 1.0,
            peak_enabled: true,
            peak_thickness: 2.0,
            peak_alpha: 0.9,
            line_thickness: 2.5,
            bar_width: 0.0,
            bar_spacing: 0.0,
            edge_spacing: 0.0,
            led_bars: false,
            led_segment_height: 6.0,
            led_border_opacity: 0.5,
            border_opacity: 0.0,
            gradient_mode: 0,
            peak_gradient_mode: 0,
            peak_mode: 2,
            peak_hold_time: 1.5,
            peak_fade_time: 0.5,
            bar_depth_3d: 0.0,
            gradient_orientation: 0,
            global_opacity: 1.0,
            lines_outline_thickness: 0.0,
            lines_outline_opacity: 0.6,
            lines_animation_speed: 0.2,
            lines_gradient_mode: 0,
            lines_fill_opacity: 0.15,
            lines_mirror: false,
            lines_glow_intensity: 0.4,
            lines_style: 0,
            scope_radius: 0.55,
            scope_sensitivity: 1.5,
            scope_particles: true,
            scope_beam: true,
            bars_flash_intensity: 0.6,
            bloom_enabled: true,
            bloom_intensity: 0.4,
            beat_reactivity: 0.7,
            trails: 0.0,
            echo: 0.0,
            crt: 0.0,
        }
    }
}
